[package]
name = "rarbg_api"
description = "A Rust wrapper for RARBG TorrentAPI"
repository = "https://github.com/baptistecdr/rarbg_api"
keywords = ["rarbg_api", "rarbg", "rarbg_wrapper", "rarbg_client", "torrent_api"]
categories = ["api-bindings"]
build = false
publish = ["crates-io"]
exclude = [".idea", "src/main.rs"]
license = "MIT"
version = "0.3.0"
authors = ["baptistecdr <baptistecdr@users.noreply.github.com>"]

[dependencies]
reqwest = { version = "0.10.4", features = ["blocking", "json"] }
serde = "1.0.106"
serde_derive = "1.0.106"
serde_json = "1.0.53"
uuid = { version = "0.8", features = ["v4"] }
