[package]
name = "rarbg_api"
version = "0.1.0"
authors = ["baptistecdr <baptistecdr@users.noreply.github.com>"]

[dependencies]
reqwest = { version = "0.10.4", features = ["blocking", "json"] }
serde = "1.0.106"
serde_derive = "1.0.106"
serde_json = "1.0.53"
uuid = { version = "0.8", features = ["v4"] }
